{
 "title": "App CUSTOM",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Darkbot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active channels per guild",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(guild_name) (darkbot_guilds_channels_gauge)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active guilds",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(guild_name) (darkbot_guilds_channels_gauge)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Viewer Requests Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(guild_name) (increase(darkbot_viewer_requests_count{error=\"\"}[5m]))",
     "legendFormat": "{{guild_name}}"
    }
   ]
  },
  {
   "title": "Viewer Requests Errors [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(channel_id, error) (increase(darkbot_viewer_requests_count{error!=\"\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "darkbot_uptime_minutes{error=\"\"}",
     "legendFormat": "{{guild_name}}"
    }
   ]
  },
  {
   "title": "Listener Requests Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(guild_name) (darkbot_listener_allowed_requests_count{error=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listener Requests Errors [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by(guild_name, error) (increase(darkbot_listener_allowed_requests_count{error!=\"\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}