{
 "title": "App Darkstat",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Http Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "darkstat_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Finished by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(darkstat_http_by_ip_finished_total[10m])) by (status_code, environment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Succesful By Ip",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_ip_finished_total{status_code=~\"2.*|3.*\", environment=\"production\"}) by (status_code, ip)",
     "legendFormat": "{{ip}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Finished Failed By Ip",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_ip_finished_total{status_code=~\"4.*|5.*\"}) by (status_code, ip)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique IPs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count (darkstat_http_by_ip_finished_total{}) by (ip))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished by Pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(darkstat_http_by_pattern_finished_total{environment=\"production\"}[10m])) by (status_code, pattern)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Failed by Pattern (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_pattern_finished_total{status_code=~\"4.*|5.*\",environment=\"production\"}) by (status_code, pattern)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Average Execution By pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(status_code, pattern) (rate(darkstat_http_by_pattern_duration_seconds_hist_sum{environment=\"production\"}[10m])) /\nsum by(status_code, pattern) (rate(darkstat_http_by_pattern_duration_seconds_hist_count{environment=\"production\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Loading Time By Pattern",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code, pattern) (darkstat_http_by_pattern_duration_seconds_sum{})",
     "legendFormat": "{{pattern}}:{{status_code}}"
    }
   ]
  },
  {
   "title": "P50 Http Execution By pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (histogram_quantile(0.50, darkstat_http_by_pattern_duration_seconds_hist_bucket{})) by (status_code, pattern, environment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 execution by pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (histogram_quantile(0.90, darkstat_http_by_pattern_duration_seconds_hist_bucket{})) by (status_code, pattern, environment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 execution by pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (histogram_quantile(0.99, darkstat_http_by_pattern_duration_seconds_hist_bucket{})) by (status_code, pattern, environment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Average Execution By pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(status_code, pattern) (rate(darkstat_http_by_pattern_duration_seconds_hist_sum{pattern!=\"index.html\"}[10m])) /\nsum by(status_code, pattern) (rate(darkstat_http_by_pattern_duration_seconds_hist_count{pattern!=\"index.html\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50-P75-P90 latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (histogram_quantile(0.50, darkstat_http_by_pattern_duration_seconds_hist_bucket{})) by (status_code, environment)",
     "legendFormat": "P50 {{environment}}, {{status_code}}"
    },
    {
     "expr": "avg (histogram_quantile(0.70, darkstat_http_by_pattern_duration_seconds_hist_bucket{})) by (status_code, environment)",
     "legendFormat": "P70 {{environment}}, {{status_code}}"
    },
    {
     "expr": "avg (histogram_quantile(0.90, darkstat_http_by_pattern_duration_seconds_hist_bucket{})) by (status_code, environment)",
     "legendFormat": "P90 {{environment}}, {{status_code}}"
    }
   ]
  },
  {
   "title": "Load By Status Code and Env",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (status_code, environment) (increase(darkstat_http_by_pattern_duration_seconds_sum{}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Body Size Sum Load By pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(status_code, pattern) (darkstat_http_by_pattern_body_size_bytes_hist_sum{environment=\"production\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Average Body Size By pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(status_code, pattern) (increase(darkstat_http_by_pattern_body_size_bytes_hist_sum{environment=\"production\"}[10m])) /\nsum by(status_code, pattern) (increase(darkstat_http_by_pattern_body_size_bytes_hist_count{environment=\"production\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Body Size P50 pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg (histogram_quantile(0.50, darkstat_http_by_pattern_body_size_bytes_hist_bucket{environment=\"production\"})) by (status_code, pattern)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Api Usages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Grpc Called Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(grpc_method) (grpc_server_msg_sent_total{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http API Called Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (darkstat_http_by_pattern_finished_total{environment=\"production\", pattern=~\"/api.*\"}) by (status_code, pattern)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}