version: '3'

tasks:
  build:folder_create:
    dir: '{{.WORKDIR}}'
    cmds:
      - mkdir build
    status:
      - test -d build

  build:package:
    dir: '{{.WORKDIR}}'
    cmds:
      - task: build:folder_create
        vars: { WORKDIR: '{{.WORKDIR}}' }
      - cue cmd build

  build:
    cmds:
      - task: build:package
        vars: { WORKDIR: 'k8s/modules/scarecrow' }
      - task: build:package
        vars: { WORKDIR: 'k8s/production' }

  cue:install:
    cmds:
      # for example PACKAGE=k8s.io/apimachinery/pkg/apis/meta/v1 task cue:install
      # for example PACKAGE=github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1 task cue:install
      - go get {{.PACKAGE}}
      - cue get go {{.PACKAGE}}