name: Trigger workflow
description: ''
inputs:
  token:
    description: Fine grained one with permission for actions:write
  repository:
    description: for example darklab8/fl-data-flsr
  workflow-file:
    description: for example publish.yaml
runs:
  using: composite
  steps:
  - name: Patch to latest
    shell: bash
    run: |
      set -e
      curl -L --fail -X POST -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{ inputs.token }}" -H "X-GitHub-Api-Version: 2026-03-10" https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow-file }}/dispatches -d '{"ref":"master","inputs":{"repo":"${GITHUB_REPOSITORY}","owner":"${GITHUB_REPOSITORY_OWNER}"}}'
