apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: github-app
    spec:
      containers:
        - name: github-pod
          image: darkwind8/github_runner:org-nodejs-14-v0.1.2
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
            - name: ORG_NAME
              value: {{ .Values.githubRunner.org }}
            - name: ORG_URL
              value: "https://github.com/{{ .Values.githubRunner.org }}"
            - name: ORG_TOKEN
              value: {{ .Values.githubRunner.tokenOrg }}
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          volumeMounts:
          - mountPath: "/var/lib/docker/aufs"
            name: scratch-volume
      volumes:
        - name: scratch-volume
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: my-volume
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 10Gi