---
- hosts: all
  become: yes
  gather_facts: true
  
  tasks:

    - name: Installing microk8s
      import_role:
        name: install_microk8s

    - name: Create data folder
      shell: mkdir -p /var/lib/darklab
