{
 "title": "TRACE metrics by metricsGenerator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total,service)"
    }
   },
   { "name": "span_name", "label": "Span Name Filtering Search", "query": ".*" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "p_latency", "query": "50,70,90,95,9999" },
   {
    "name": "span_kind",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{service=\"$service\"},span_kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request Per $interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_calls_total{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$interval])) by(service)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Tracing Span Error Rate in $interval",
   "type": "timeseries",
   "description": "request rate per minute over last 3 minutes",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (client, server)(increase(traces_service_graph_request_failed_total{service=~\"${service}\", span_name=~\"$span_name\"}[$interval])) OR on() vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Calls Count Distribution",
   "type": "piechart",
   "description": "request amount distribution",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_calls_total{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$__range])) by (span_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loading Distribution",
   "type": "piechart",
   "description": "cumulative latency distribution",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_latency_sum{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$__range])) by (span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Overall Request Rate Per $interval",
   "type": "gauge",
   "description": "overall request rate per minute over last 3 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_calls_total{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "gauge",
   "description": "percentage of HTTP status 5xx in all requests",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_service_graph_request_failed_total{span_kind=~\"$span_kind\",service=~\"${service}\"}[$interval])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Request Rate Per $interval",
   "type": "timeseries",
   "description": "request rate per minute over last 3 minutes",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_calls_total{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$interval]))  by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Latency in $interval",
   "type": "timeseries",
   "description": "by route and http status code",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_sum{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$interval])) by (span_name) / sum(rate(traces_spanmetrics_latency_count{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$interval])) by (span_name)",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "P$p_latency Latency in $interval",
   "type": "timeseries",
   "description": "P$p_latency latency over last 3 minutes",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$p_latency, sum(rate(traces_spanmetrics_latency_bucket{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$interval])) by (le, span_name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Sum Load Time per Span in $interval",
   "type": "timeseries",
   "description": "by route and http status code",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_latency_sum{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$interval])) by (span_name)",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Web endpoints Details",
   "type": "table",
   "description": "Details of each API",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_calls_total{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$interval]) OR on() vector(0)) by(service, span_name)"
    },
    {
     "expr": "sum(increase(traces_spanmetrics_latency_sum{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$__range]) OR on() vector(0)) by (le, service_name, span_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$interval]) OR on() vector(0)) by (le, service_name, span_name))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{span_kind=~\"$span_kind\",service=~\"${service}\", span_name=~\"$span_name\"}[$interval]) OR on() vector(0)) by (le, service_name, span_name))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}