name: Checkout freelancer
description: ""
inputs:
  freelancer-folder:
    description: Path to root of freelancer directory
    default: ${{ github.workspace }}
  freelancer-mod:
    description: insert vanilla or discovery
    required: true
  ssh-key-base64-vanilla:
    description: Key to download Freelancer vanilla repo
    default: ''
  ssh-key-base64-discovery:
    description: Key to download Discovery repo
    default: ''

runs:
  using: "composite"
  steps:
    - name: Write vanilla id_rsa down
      if: ${{ inputs.freelancer-mod == 'vanilla' }}
      shell: python
      run: |
        import base64
        import os
        file_output_name = "${{ github.workspace }}/id_rsa.out"
        with open(file_output_name, "wb", 0o600) as file:
          file.write(base64.b64decode(bytes(os.environ["ID_RSA_FILE_IN_BASE64"], encoding='utf8')))
        os.chmod(file_output_name, 0o600)
      env:
        ID_RSA_FILE_IN_BASE64: ${{ inputs.ssh-key-base64-vanilla }}
    - name: Write discovery id_rsa down
      if: ${{ inputs.freelancer-mod == 'discovery' }}
      shell: python
      run: |
        import base64
        import os
        file_output_name = "${{ github.workspace }}/id_rsa.out"
        with open(file_output_name, "wb", 0o600) as file:
          file.write(base64.b64decode(bytes(os.environ["ID_RSA_FILE_IN_BASE64"], encoding='utf8')))
        os.chmod(file_output_name, 0o600)
      env:
        ID_RSA_FILE_IN_BASE64: ${{ inputs.ssh-key-base64-discovery }}
    - shell: sh
      run: > 
        GIT_SSH_COMMAND='ssh -i ${{ github.workspace }}/id_rsa.out -o IdentitiesOnly=yes'
        git clone git@github.com:darklab8/fl-files-${{ inputs.freelancer-mod }}.git
    - shell: sh
      run: mv fl-files-${{ inputs.freelancer-mod }} ${{ inputs.freelancer-folder }} | true
