---
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600

  - name: Wait for APT Lock
    shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

  - name: Install snapd
    apt:
      name: snapd
      state: present

  - name: Install "microk8s" with option --classic
    community.general.snap:
      name: microk8s
      classic: yes
      # channel: 1.28/stable # risking update always to keep up with k8s

  - name: Await microk8s starting cluster
    shell: microk8s status --wait-ready

  - name: Microk8s - enabling DNS and storage
    shell: microk8s enable dns hostpath-storage
